// Mock data store for the helpdesk system
export const mockData = {
  // Tenants
  tenants: [
    {
      id: 1,
      name: "Acme Corp",
      email: "admin@acmecorp.com",
      agents: 12,
      customers: 342,
      status: "active",
      joinDate: "2024-01-15",
      plan: "enterprise",
      channels: {
        whatsapp: "+919876543210",
        telegram: "@acmecorp_support",
        phone: "+919876543211",
        email: "support@acmecorp.com",
      },
      webhookToken: "wh_acme_abc123xyz789", // Unique token for this tenant
    },
    {
      id: 2,
      name: "Tech Startup Inc",
      email: "contact@techstartup.com",
      agents: 8,
      customers: 289,
      status: "active",
      joinDate: "2024-02-20",
      plan: "professional",
      channels: {
        whatsapp: "+919876543220",
        telegram: "@techstartup_support",
        phone: "+919876543221",
        email: "support@techstartup.com",
      },
      webhookToken: "wh_tech_def456uvw012",
    },
    {
      id: 3,
      name: "Global Services Ltd",
      email: "admin@globalservices.com",
      agents: 10,
      customers: 256,
      status: "active",
      joinDate: "2024-03-10",
      plan: "professional",
      channels: {
        whatsapp: "+919876543230",
        telegram: "@globalservices_support",
        phone: "+919876543231",
        email: "support@globalservices.com",
      },
      webhookToken: "wh_global_ghi789rst345",
    },
    {
      id: 4,
      name: "Enterprise Solutions",
      email: "info@enterprise.com",
      agents: 15,
      customers: 512,
      status: "active",
      joinDate: "2023-12-01",
      plan: "enterprise",
      channels: {
        whatsapp: "+919876543240",
        telegram: "@enterprise_support",
        phone: "+919876543241",
        email: "support@enterprise.com",
      },
      webhookToken: "wh_enterprise_jkl012mno678",
    },
  ],

  // Agents
  agents: [
    {
      id: 1,
      name: "Alice Johnson",
      email: "alice@company.com",
      status: "online",
      ticketsAssigned: 8,
      resolved: 156,
      satisfaction: 4.8,
      joinDate: "2024-01-10",
      tenantId: 1,
    },
    {
      id: 2,
      name: "Bob Smith",
      email: "bob@company.com",
      status: "online",
      ticketsAssigned: 6,
      resolved: 142,
      satisfaction: 4.7,
      joinDate: "2024-02-15",
      tenantId: 1,
    },
    {
      id: 3,
      name: "Carol Davis",
      email: "carol@company.com",
      status: "away",
      ticketsAssigned: 4,
      resolved: 138,
      satisfaction: 4.6,
      joinDate: "2024-03-20",
      tenantId: 1,
    },
    {
      id: 4,
      name: "David Wilson",
      email: "david@company.com",
      status: "offline",
      ticketsAssigned: 0,
      resolved: 124,
      satisfaction: 4.5,
      joinDate: "2024-04-05",
      tenantId: 1,
    },
  ],

  // Tickets
  tickets: [
    {
      id: "TKT-1001",
      title: "Critical: System Performance Degradation",
      description: "System experiencing slow response times",
      priority: "Critical",
      status: "Open",
      tenant: "Acme Corp",
      tenantId: 1,
      agent: "Alice Johnson",
      customer: "John Doe",
      created: "2025-10-31",
      updated: "2025-10-31",
      category: "technical",
      responses: 3,
    },
    {
      id: "TKT-1002",
      title: "Feature Request: Custom Branding",
      description: "Add ability to customize dashboard branding",
      priority: "Medium",
      status: "In Progress",
      tenant: "Tech Startup Inc",
      tenantId: 2,
      agent: "Bob Smith",
      customer: "Jane Smith",
      created: "2025-10-30",
      updated: "2025-10-31",
      category: "feature",
      responses: 2,
    },
    {
      id: "TKT-1003",
      title: "Bug: Email Notifications Not Sending",
      description: "Email notifications are not being delivered",
      priority: "High",
      status: "Open",
      tenant: "Global Services Ltd",
      tenantId: 3,
      agent: "Carol Davis",
      customer: "Mike Johnson",
      created: "2025-10-29",
      updated: "2025-10-31",
      category: "bug",
      responses: 5,
    },
    {
      id: "TKT-2001",
      title: "Cannot reset password",
      description: "User unable to reset password on mobile",
      priority: "High",
      status: "In Progress",
      tenant: "Acme Corp",
      tenantId: 1,
      agent: "Alice Johnson",
      customer: "Sarah Wilson",
      created: "2025-10-31",
      updated: "2025-10-31",
      category: "technical",
      responses: 1,
    },
    {
      id: "TKT-2002",
      title: "Billing inquiry about subscription",
      description: "Questions about invoice and charges",
      priority: "Medium",
      status: "Resolved",
      tenant: "Tech Startup Inc",
      tenantId: 2,
      agent: "Bob Smith",
      customer: "Tom Brown",
      created: "2025-10-28",
      updated: "2025-10-29",
      category: "billing",
      responses: 2,
    },
    {
      id: "TKT-3001",
      title: "Login issues on mobile app",
      description: "Cannot login on iOS app",
      priority: "High",
      status: "Open",
      tenant: "Acme Corp",
      tenantId: 1,
      agent: "Carol Davis",
      customer: "Lisa Anderson",
      created: "2025-10-31",
      updated: "2025-10-31",
      category: "technical",
      responses: 0,
    },
    {
      id: "TKT-3002",
      title: "Feature request: Dark mode",
      description: "Request for dark mode support",
      priority: "Low",
      status: "In Progress",
      tenant: "Acme Corp",
      tenantId: 1,
      agent: "Alice Johnson",
      customer: "Mark Davis",
      created: "2025-10-30",
      updated: "2025-10-31",
      category: "feature",
      responses: 1,
    },
    {
      id: "TKT-3003",
      title: "Payment processing error",
      description: "Payment failed with error code",
      priority: "Critical",
      status: "Open",
      tenant: "Global Services Ltd",
      tenantId: 3,
      agent: "David Wilson",
      customer: "Jennifer Lee",
      created: "2025-10-29",
      updated: "2025-10-31",
      category: "billing",
      responses: 4,
    },
  ],

  // Customers
  customers: [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      company: "Acme Corp",
      status: "active",
      tickets: 5,
      joinDate: "2024-01-15",
      tenantId: 1,
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane@example.com",
      company: "Tech Startup Inc",
      status: "active",
      tickets: 3,
      joinDate: "2024-02-20",
      tenantId: 2,
    },
    {
      id: 3,
      name: "Mike Johnson",
      email: "mike@example.com",
      company: "Global Services Ltd",
      status: "active",
      tickets: 2,
      joinDate: "2024-03-10",
      tenantId: 3,
    },
    {
      id: 4,
      name: "Sarah Wilson",
      email: "sarah@example.com",
      company: "Acme Corp",
      status: "active",
      tickets: 7,
      joinDate: "2024-01-20",
      tenantId: 1,
    },
  ],

  // Knowledge Base Articles
  articles: [
    {
      id: 1,
      title: "How to create an account",
      category: "Getting Started",
      views: 1203,
      likes: 234,
      content: "Step-by-step guide to create your account...",
    },
    {
      id: 2,
      title: "Setting up your profile",
      category: "Getting Started",
      views: 856,
      likes: 145,
      content: "Learn how to set up your profile...",
    },
    {
      id: 3,
      title: "How to update billing information",
      category: "Account & Billing",
      views: 1456,
      likes: 234,
      content: "Guide to updating your billing details...",
    },
    {
      id: 4,
      title: "Troubleshooting login issues",
      category: "Technical Support",
      views: 2456,
      likes: 456,
      content: "Common login issues and solutions...",
    },
  ],

  // Comments
  comments: [
    {
      id: 1,
      ticketId: "TKT-1001",
      author: "Alice Johnson",
      role: "Agent",
      text: "I'm looking into this issue now.",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      attachments: [],
    },
    {
      id: 2,
      ticketId: "TKT-1001",
      author: "John Doe",
      role: "Customer",
      text: "Thank you for your quick response!",
      timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      attachments: [],
    },
  ],

  // Activities
  activities: [
    {
      id: 1,
      ticketId: "TKT-1001",
      action: "created",
      description: "Ticket created",
      user: "John Doe",
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    {
      id: 2,
      ticketId: "TKT-1001",
      action: "assigned",
      description: "Assigned to Alice Johnson",
      user: "System",
      timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    },
    {
      id: 3,
      ticketId: "TKT-1001",
      action: "status_changed",
      description: "Status changed to In Progress",
      user: "Alice Johnson",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
  ],

  // Uploaded Files
  uploadedFiles: [
    {
      id: 1,
      ticketId: "TKT-1003",
      name: "error-log.txt",
      size: 125000,
      type: "text/plain",
      uploadedBy: "Mike Johnson",
      uploadedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    {
      id: 2,
      ticketId: "TKT-3001",
      name: "screenshot.png",
      size: 245000,
      type: "image/png",
      uploadedBy: "Lisa Anderson",
      uploadedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    },
  ],
}
